### ISSUE TITLE
[2주차 과제] 날씨 앱 클론코딩 - 지역 목록, 상세정보 화면

### ISSUE THREAD

**Issue by Naknakk** [DO-SOPT-iOS-Part/LeeYunhak-assignment#1]
## Description
- 2차 세미나 과제
- Code-Based UI, 오토레이아웃, StackView, ScrollView 등 세미나 내용에 익숙해지기.

## To-do
- [x] 시작화면에서 해당 나의 위치 뷰를 선택하면, 우측의 날씨 상세보기뷰로 Push되어 이동합니다.
- [x] 상세보기뷰는 수직 스크롤이 가능하고, 중간의 시간대별 날씨의 경우 수평스크롤이 가능해야 합니다. 
- [x] 하단의 리스트 보기 버튼을 선택할 경우, 시작화면으로 POP되면 됩니다.
